teslajsonpy/BatterySensor.py
teslajsonpy/BinarySensor.py
teslajsonpy/Charger.py
teslajsonpy/Climate.py
teslajsonpy/GPS.py
teslajsonpy/Lock.py
teslajsonpy/controller.py

This is necessary to the extent a vehicle is unavailable and returns a false value in response to get(car_id, 'data').  Relevant state data will not be updated for each component. It may make sense to make the initial values for every state also return a false value and have further clients (e.g., Homeassistant Tesla component) properly parse false values as unknown until valid data is saved.

Adding checks for valid vehicle data before updating values

---

teslajsonpy/controller.py
teslajsonpy/vehicle.py

Should resolve #18. 
Also add an exponential growing delay counter for wake up retries. With 5 default retries, the delays should happen after 4, 8, 16, 32, 64 seconds with total time elapsed of 4, 12, 28, 60, and 124 seconds before failure. This may have to be dialed back as it could block commands while waiting for wakeup.

Add logic to only poll awake vehicles

---

setup.py
teslajsonpy/BatterySensor.py
teslajsonpy/BinarySensor.py
teslajsonpy/Charger.py
teslajsonpy/Climate.py
teslajsonpy/Exceptions.py
teslajsonpy/GPS.py
teslajsonpy/Lock.py
teslajsonpy/connection.py
teslajsonpy/controller.py
teslajsonpy/vehicle.py

- Add wake_up and retry logic decorators for get and post functions.  Fixes (#16, #28)
- Add wake_if_asleep parameter to avoid waking vehicles. Commands should set to True; updates to False.  Resolves (#18)

Fix bugs where car would not wake for command

---

Makefile
Pipfile
Pipfile.lock
README.md
pylintrc
setup.cfg
teslajsonpy/__init__.py
teslajsonpy/__version__.py
teslajsonpy/battery_sensor.py
teslajsonpy/binary_sensor.py
teslajsonpy/charger.py
teslajsonpy/climate.py
teslajsonpy/connection.py
teslajsonpy/controller.py
teslajsonpy/exceptions.py
teslajsonpy/gps.py
teslajsonpy/lock.py
teslajsonpy/vehicle.py

This version contains numerous changes in addition to the async conversion. It includes a new charging sensor, support for oauth, performance tweaks, and incorporation of black for formatting.
BREAKING CHANGE: API calls now require async
Closes #44, #47

feat: convert to async

---

Pipfile
Pipfile.lock
setup.py
teslajsonpy/__init__.py
teslajsonpy/battery_sensor.py
teslajsonpy/binary_sensor.py
teslajsonpy/charger.py
teslajsonpy/climate.py
teslajsonpy/connection.py
teslajsonpy/const.py
teslajsonpy/controller.py
teslajsonpy/exceptions.py
teslajsonpy/gps.py
teslajsonpy/lock.py
teslajsonpy/vehicle.py

Needs following update to [HA](https://github.com/home-assistant/home-assistant/compare/dev...alandtse:websocket?expand=1) to test.
Apparently Tesla only allows one app to consume websockets at a time so may block other apps from gathering location info. This is now enabled as an integration option.

feat: add websocket support

---

AUTHORS.md
teslajsonpy/__init__.py
teslajsonpy/controller.py
teslajsonpy/sentry_mode.py

Add a switch to enable/disable sentry mode for Tesla vehicle in Home Assistant. This should fix issue #43.

feat: add sentry mode switch to fix issue #43

---

teslajsonpy/sentry_mode.py
teslajsonpy/vehicle.py

Similar to PR #64, and as requested in PR #61, remove check for current state in case it is not accurate.

fix: remove checks for state for sentry mode

---

setup.py

`bs4` is a only dummy module for `beautifulsoup4`.

Don't use dummy module

---

teslajsonpy/teslaproxy.py

With a delay below 10 seconds, it would be a login could be interrupted
by the refresh. Increased to a minimum of 10 seconds.

fix: increase delay for refresh and update message

---

tests/tesla_mock.py
tests/unit_tests/homeassistant/test_online_sensor.py

Deep copy mock data to avoid cross-test pollution

---

poetry.lock
pyproject.toml
teslajsonpy/connection.py
teslajsonpy/controller.py
teslajsonpy/teslaproxy.py

aiohttp appears to have issues related to Akamai Global Host and
developers do not seem interested in resolving as a bug.
https://github.com/aio-libs/aiohttp/issues/5643
BREAKING CHANGE: API has changed due to use of httpx. Modifiers, test_url, and other items that access aiohttp ClientResponse will need to be fixed.
Closes #190
Will need https://github.com/alandtse/auth_capture_proxy/pull/13

feat: swap to httpx

---

teslajsonpy/connection.py

Fixes
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 264, in async_setup
result = await component.async_setup_entry(hass, self)  # type: ignore
File "/usr/src/homeassistant/homeassistant/components/tesla/__init__.py", line 163, in async_setup_entry
result = await controller.connect(
File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 288, in connect
cars = await self.get_vehicles()
File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 407, in get_vehicles
return (await self.__connection.get("vehicles"))["response"]
File …
```

Check response before json

---

teslajsonpy/connection.py

Throws an exception when calling refresh_access_token that the URL parameter is nether a string nor a httpx.Url

Fix bug in refresh_access_token

---

teslajsonpy/connection.py

This fix will allow a user to provide a refresh token generated by apps like "AuthAppForTesla" etc to authenticate. This is the way Telsamate, Teslascope and others are authenticating and it works.
This will require that the core Tesla integration in Home Assistant is updated to be able to provide the refresh_token, but this change is a prerequisite.
Related issue #205.

fix: allow auth using refresh_token

---

teslajsonpy/connection.py
teslajsonpy/controller.py

Hey,
This will return the id_token as well so that we can use PyJwt in the component to extract the email from the token directly.
```python
import jwt
[...]
def get_email_from_id_token(id_token: str):
decoded = jwt.decode(id_token, options={"verify_signature": False, "verify_aud": False})
return decoded["email"] if "email" in decoded else None
```
It also sets the refresh_token to the correct refresh token. The current version returns the refresh_token from the owner-api and that's not used for anything. 
See https://tesla-api.timdorr.com/api-basics/authentication#post-https-auth-tesla-com-oauth-2-v-3-token-1
> This uses the SSO refresh_token from Step 3 above to do an OAuth 2.0 Refresh Token Grant. This does not work with the refresh_token provided by the Owner API. Those have no use …

Add id_token to connect() response and return correct refresh_token

---

AUTHORS.md
teslajsonpy/homeassistant/charger.py
tests/unit_tests/homeassistant/test_charging_sensor.py

Here is a PR to expose Charger's charge_current_request_max variable.  
I have a use case where I have multiple chargers (and cars) with different maximum charge capabilities. It would be really helpful to have max exposed so that I know up-front how much current I can push to each one by querying this variable.
Thanks

Expose max charger variable

---

teslajsonpy/controller.py

When using the `connect()` method with filtered vins and then calling update, you would get a KeyValue error because it would try to update a dict on a key that does not exist.

fix(vins): ensure vin is in saved state before updating

---

teslajsonpy/homeassistant/power.py
tests/tesla_mock.py
tests/unit_tests/homeassistant/test_power_sensor.py

I have a solar city system from 2007 that is now in Tesla's system. It has the following response for the `live_status` endpoint:
```json
{
"response": {
"solar_power": 1760,
"grid_status": "Unknown",
"grid_services_active": false,
"timestamp": "2021-12-24T13:09:39-08:00"
}
}
```
Because of the `grid_status` its value was not updating in homeassistant.

fix(energysites): changing unknown grid status logic

---

teslajsonpy/homeassistant/binary_sensor.py
tests/unit_tests/homeassistant/test_online_sensor.py

Not all data available through the API is exposed in the sensors to home assistant. Due to amount of available data it also won't make sense to expose everything as sensors or attributes.
This PR adds a new attribute (vehicle_data) to the binary OnlineSensor containing all the information retrieved from the API as a json string.
This then allows one to extract the data in templates and use as sensors.
For example, to get third row left seat heater in Model X:
```
{{ (state_attr('binary_sensor.<name>_online_sensor', 'vehicle_data') | from_json)['climate_state']['seat_heater_third_row_left'] }}
```

Provide all data in home assistant sensor as json string

---

teslajsonpy/const.py
teslajsonpy/controller.py
teslajsonpy/homeassistant/binary_sensor.py
tests/unit_tests/test_polling_interval.py

This PR adds the option for per vehicle polling interval. Through this one can set the polling interval based on each vehicle and thus have a higher polling frequency for 1 vehicle whereas keeping it at a lower polling frequency for another vehicle allowing it to go to sleep.
If no polling interval is set for a VIN then the polling interval is used that has been set for the coordinator.
One can also provide a value of -1 or None as polling interval for a VIN which will then remove that per VIN interval and thus go back to the polling interval for the coordinator.

Add per vehicle polling interval

---

setup.cfg
teslajsonpy/connection.py
teslajsonpy/controller.py
teslajsonpy/homeassistant/binary_sensor.py
teslajsonpy/homeassistant/gps.py

https://github.com/alandtse/tesla/issues/165

Remove get bearer token step

---

teslajsonpy/homeassistant/vehicle_data.py

This fixes a breaking change for users running python 3.8 and lower that was introduced in #299 
Type-hinting the contents of a list require importing `List` from typing on python versions prior to 3.9
Tested with `make coverage` on python 3.8.10

fix: use typing.List for typehint to support python < 3.9

---

teslajsonpy/controller.py

Sensor ChargeStateDataSensor was added twice to list of components for vehicle resulting in warning within HASS that component is not creating sensors with unique IDs. This did not cause any other issues within HASS.
This PR just removes that duplicate line entry

Remove duplicate ChargeStateDataSensor

---

teslajsonpy/homeassistant/heated_seats.py
teslajsonpy/homeassistant/heated_steering_wheel.py

When a car doesn't have a heated steering wheel, teslajsonpy would throw an index error.
simply updating this to a get so it returns None, which is a valid response.
I've also updated heated seats, which used the same code.
Resolves
https://github.com/alandtse/tesla/issues/199

Not all cars have heated steering wheels and seats

---

teslajsonpy/homeassistant/power.py

Some systems that pre-date Tesla aquisition of SolarCity will have `grid_status: Unknown`, but will have solar power values. At the same time, newer systems will report spurious reads of 0 Watts and grid status "Unknown". In this case, if solar power is 0 return null.
Solves #287

Improved handling on 0 Watts spurious power reads

---

AUTHORS.md
teslajsonpy/controller.py
teslajsonpy/homeassistant/power.py
tests/tesla_mock.py
tests/unit_tests/homeassistant/test_power_sensor.py

Initial commit to add grid and home (aka load) sensors for Tesla solar systems. All Tesla solar customers with Powerwall should have grid and home reporting as well as non-Powerwall customers with a Tesla inverter and Neurio energy monitoring device, which is what I have. Not all non-Powerwall customers will have a Neurio energy monitoring device as Tesla is not consistent on when they install them. However, I suspect the JSON structure is the same but they will just report back with a value of 0.
Specific changes:
- ~~Added new method `get_site_data` to controller.py. This uses the `SITE_DATA` endpoint where the grid and load power values are located.~~
- ~~During initialization of `Controller`, call `get_site_data` and append it with the `PRODUCT_LIST`~~ Add `load_power` and …

Initial commit to add grid and load sensors

---

teslajsonpy/homeassistant/power.py
tests/unit_tests/homeassistant/test_power_sensor.py

Apologize I didn't catch this earlier but the only reason the previous solar panel sensor was being recreated was because I updated the name to match the naming convention of the other sensors. The name is used as a part of the UUID in Home Assistant which was causing a new solar power sensor to be created. I just reverted back to the original name, solar panel, so it doesn't create a breaking change.

Revert name to prevent breaking change

---

teslajsonpy/controller.py
teslajsonpy/homeassistant/power.py
tests/unit_tests/homeassistant/test_power_sensor.py

Fixes:
- Fixes [key error issue](https://github.com/alandtse/tesla/issues/254) for energy sites that don't have load meters. Added a check to not add the grid and load sensor unless `load_meter` is `True` from Tesla's API response.
- Adds some checks to deal with the [issue](https://github.com/alandtse/tesla/issues/248) where some energy sites don't report `grid_status` (i.e. always `Unknown`) and other sites do but with spurious power readings at times.

Fix grid status and load sensor issues

---

teslajsonpy/controller.py
teslajsonpy/homeassistant/power.py

Fixes an issue that was identified where `grid_status` is actually not reported when the state is `Active` in certain setups.
Sorry for all the changes @alandtse. Not having JSON responses on the various energy site setups and cases is proving to be a pain.

Fix for grid_status case

---

teslajsonpy/homeassistant/charger.py

Version 2022.36 seems to not include charge_to_max_range.
This uses charge_limit_soc[_max] to determine it if charge_to_max_range is not available

Add fix for api change in version 2022.36 (missing charge_to_max_range)

---

AUTHORS.md
teslajsonpy/car.py
tests/unit_tests/test_car.py

This PR adds a is_window_open parameter that will return 1 if any window is open. It also adds a close_windows and vent_windows function. This has been working from Home Assistant with the custom_api calls. 
I need to figure out how to run the tests. ~~"make init" in terminal did not recognize "make". Any guidance on the tests or the code is appreciated.~~
~~Got make installed fine, receiving this error "Expecting value: line 1 column 1 (char 0)". I'll keep poking.~~
All good now, tests are working on my end.

feat: Add window control and window binary sensor

---

teslajsonpy/car.py
tests/tesla_mock.py
tests/unit_tests/test_car.py

For https://github.com/alandtse/tesla/issues/359
This PR adds a `usable_battery_level` method in `TeslaCar`. The official Tesla app and in-car display shows the usable battery level value, which is affected by temperature (apparent when you see a snowflake icon). By adding this method, we can update the HA integration to use this new method for the car's battery level sensor so that it matches the official app.

feat: Add usable_battery_level method in TeslaCar

---

teslajsonpy/controller.py

This should fix a couple of related issues:
- https://github.com/alandtse/tesla/issues/324
- https://github.com/alandtse/tesla/issues/315
If `get_vehicle_data` failed for a TeslaException that wasn't a 408, it would try to return an unassigned variable. Now it will re-raise that "unexpected" exception to let the caller handle it.
Additionally the calls for `get_vehicle_data` in `generate_car_objects` did not handle a vehicle being offline gracefully, and would fail the entire integration setup. The same was for `generate_energysite_objects` for a very similar reason.
Now if the vehicle/site data is unavailable during setup, the device will still be added with the data dict empty. Each of the car/site classes are designed to handle an empty data dictionary, so this should be fine. From …

fix: graceful handling of unavailable sites/vehicles.

---

teslajsonpy/car.py
tests/unit_tests/test_car.py

I missed this paragraph about the valet mode command in [Tesla JSON API](https://tesla-api.timdorr.com/vehicle/commands/valet#post-api-1-vehicles-id-command-set_valet_mode).
```
Note: the password parameter isn't required to turn on or off Valet Mode, even with a previous PIN set. If you clear the PIN and activate Valet Mode without the parameter, you will only be able to deactivate it from your car's screen by signing into your Tesla account.
```
Turning valet mode on and off from the app does not require the pin. That argument is useful for setting a cleared pin. Not useful if the pin is already set.

fix: Valet mode optional argument

---

teslajsonpy/car.py

Sorry I missed this, the correct key was 'password' not 'pin'.
https://tesla-api.timdorr.com/vehicle/commands/valet#post-api-1-vehicles-id-command-set_valet_mode

fix: valet mode parameter name wrong

---

teslajsonpy/car.py

Closes https://github.com/alandtse/tesla/issues/379
This strategically checks if some commands would be pointless if the car is asleep, and sets `wake_if_asleep` accordingly.
Also refactors default parameters to save ~100 lines
(this is split out from #373)

fix: Don't wake car for pointless commands

---

poetry.lock
pyproject.toml
teslajsonpy/const.py
teslajsonpy/controller.py
teslajsonpy/exceptions.py
tests/unit_tests/test_exceptions.py

To combat transient api exceptions such as 408 when the vehicle has limited connectivity, the retry logic has been updated to handle `TeslaException` as well the existing `httpx.RequestError`
- multiple existing retry decorators for `httpx.RequestError` were refactored to a single `__post_with_retries` method since they all had the same parameters anyway
- `__post_with_retries` method added to decorate the api post as late as possible in the chain to prevent more high level logic from getting caught up in retries (such as the wake up logic), and ensuring the retries are as fast as possible
- `backoff` library replaced by `tenacity` library to give more flexibility in the retry logic, as well as to avoid some known timing bugs that `backoff` had.
- refactors the giveup logic into a …

feat: include TeslaExceptions for api retries

---

AUTHORS.md
teslajsonpy/car.py
tests/unit_tests/test_car.py

When calling `set_charging_amps` it looks for a parameter `charge_amps` and uses this to save the updated value, however this parameter isnt used anywhere else. I believe this is actually meant to be the `charge_current_request` parameter.
Fixes https://github.com/alandtse/tesla/issues/479

fix: Replace charge_amps with charge_current_request in set_charging_amps

---

teslajsonpy/controller.py

When a user has multiple energy sites/cars they all update even if the device is disabled in Home Assistant
Related PR https://github.com/alandtse/tesla/pull/552

feat: add energy_site_ids and vins to update to limit updating to specific devices

---

teslajsonpy/car.py
tests/unit_tests/test_car.py

Home Assistant sometimes throws the following error on startup
```
Traceback (most recent call last):
File "/config/custom_components/tesla_custom/teslamate.py", line 208, in msg_recieved
).result()
File "/usr/local/python/lib/python3.10/concurrent/futures/_base.py", line 446, in result
return self.__get_result()
File "/usr/local/python/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
raise self._exception
File "/config/custom_components/tesla_custom/teslamate.py", line 237, in async_handle_new_data
coordinator.async_update_listeners()
File "/usr/local/python/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
update_callback()
File "/config/custom_components/tesla_custom/base.py", line 40, in refresh …
```

fix: don't assume climate_state exists

---

teslajsonpy/car.py
teslajsonpy/controller.py
teslajsonpy/exceptions.py

We would retry on 408s even if wake_if_asleep was False which slowed down startup a lot for cars we did not wake
Before: startup 145.3s
After: startup 15.2s

fix: avoid retry on sleep/unavailable when the car is asleep with wake_if_asleep=False

---

teslajsonpy/energy.py

These were implemented as `.get()` but there was no default so it would fail anyways
fixes
```
2023-07-24 12:56:40.749 ERROR (MainThread) [homeassistant.components.number] Error while setting up tesla_custom platform for number
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 670, in _async_add_entity
original_icon=entity.icon,
^^^^^^^^^^^
File "/config/custom_components/tesla_custom/number.py", line 142, in icon
return …
```

fix: missing defaults in energysite

---

teslajsonpy/endpoints.json

After upgrading to 2023.38.* the Tesla API requires specifying the query parameter `endpoints` when asking for location data from the vehicle. Supply this parameter along with other parameters needed to fetch the vehicle data.
I didn't really test this properly except via the home assistant plugin, so more testing may be needed.
This change corresponds to the changes in `teslamate` and `TeslaPy`:
https://github.com/tdorssers/TeslaPy/commit/38ff7da6e5a7aa1fcd5d39b84aa1d89c9cff50b5
https://github.com/adriankumpf/teslamate/commit/5058a6fa07f3fae2f1552c7150b28481446967c5
API Documentation:
https://developer.tesla.com/docs/fleet-api#vehicle_data
Fixes #434

fix: Supply 'endpoints' parameter to vehicle_data endpoint

---

teslajsonpy/endpoints.json

For some reason, the Tesla API sometimes do not return all the data unless the semicolons in the endpoints parameter are URL encoded.
Replace ; with %3B which is the URL encoded value.

fix: escape semicolons in vehicle_data endpoint

---

poetry.lock
teslajsonpy/controller.py
teslajsonpy/energy.py

The contributing guide advises to run `make lint`. I fixed all existing ones in this separate PR before starting to add my own new errors.
Before:
```
(teslajsonpy-py3.11) ~/src/teslajsonpy (dev ✗) make lint
poetry run flake8 teslajsonpy
teslajsonpy/controller.py:342:1: W293 blank line contains whitespace
teslajsonpy/controller.py:347:10: W291 trailing whitespace
teslajsonpy/controller.py:415:1: W293 blank line contains whitespace
teslajsonpy/controller.py:425:67: W291 trailing whitespace
teslajsonpy/controller.py:426:1: W293 blank line contains whitespace
teslajsonpy/controller.py:428:25: E126 continuation line over-indented for hanging indent
teslajsonpy/controller.py:429:21: E121 continuation line under-indented for hanging indent
teslajsonpy/controller.py:429:22: W291 trailing …
```

style: fix whitespace and formatting

---

teslajsonpy/controller.py
teslajsonpy/endpoints.json

This should resolve issue #448 for pre-2021 Model X/Model S cars.
Based on the changes described in https://github.com/alandtse/tesla/issues/774#issuecomment-1917821933
It won't necessarily help with newer cars, but should do no harm.
Tested with 2017 MX.

fix: Remove references to deprecated vehicles endpoint.

---

teslajsonpy/controller.py

Previously we would gather which would open a flood of connections and since the cost of establishing the TLS connection `do_handshake` was higher than the actual request, it would take more wall clock time to update and was more resource intensive.

fix: maximize chance of reusing the connection while updating

---

AUTHORS.md
teslajsonpy/connection.py

When using the older Owner API, the client_id string should be literally `ownerapi`.  There doesn't seem to be any use for the old client_id and client_secret which was previously included in this code.
Fixes #459.

fix: remove old client_id

---

AUTHORS.md
teslajsonpy/energy.py
tests/unit_tests/test_energy.py

I recently had a Powerwall 3 installed, and I have no local API access. I'm using [Tesla Custom Integration](https://github.com/alandtse/tesla) to integrate the battery into my Home Assistant setup via the owner cloud. The grid status binary sensor provided by that integration always inaccurately showed as 'Clear' or `off`. I traced this back to the `PowerwallSite.grid_status` property in this project. Changing this property to lookup the value in `self._site_data` instead of `self._site_summary` fixed the issue for me. Your test mock data suggests that site data was always the correct source, but I do not have access to any other powerwalls to see if this is unique to Powerwall 3 cloud access.

fix: fix grid_status

---

teslajsonpy/car.py

https://github.com/alandtse/tesla/issues/957 under Tesla Custom Integration
Tesla seems to have changed the API call for REMOTE_SEAT_HEATER_REQUEST without documenting the change. Instead of the parameter "heater", it now wants "seat_position".

fix: fix heated seats parameter change

---

teslajsonpy/connection.py

When doing an API call for which the method is get but where parameters are provided an exception occurs for unknown attribute json=data.
This is due to the  httpx get method not supporting the json parameter, instead the params parameter has to be provided.
This fixed checks if the method is get and if it is will provide the additional parameters through params parameter instead.

fix: json attribute error for GET with parameters

---

teslajsonpy/controller.py

When both websession and api_proxy_cert are provided to Controller then following error is reported:
`UnboundLocalError: cannot access local variable 'ssl_context' where it is not associated with a value`.
This PR fixes this issue by only checking if certificate is valid if websession is  provided.

fix: UnboundLocalError in controller when both websession and api_proxy_cert are provided.

---

teslajsonpy/controller.py

Fix for when both websession and api_proxy_cert are provided.

fix: UnboundLocalError when both websession and api_proxy_cert provided

---

teslajsonpy/energy.py

I found another issue related to my replaced Powerwall 3. The `_site_config` for the old powerwall does not include a `nameplate_energy` key. For my new powerwall, this entry has a value of 0, but the key is at least part of the payload. I added a default value to this one also.
Here's the stack trace from HA:
```text
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
self.async_write_ha_state()
~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
self._async_write_ha_state() …
```

fix: Add default value to nameplate_energy get
