zabuldon/teslajsonpy

teslajsonpy/BatterySensor.py, teslajsonpy/BinarySensor.py, teslajsonpy/Charger.py, teslajsonpy/Climate.py, teslajsonpy/GPS.py, teslajsonpy/Lock.py, teslajsonpy/__init__.py, teslajsonpy/controller.py
Added odometer and range sensors and a switch to set maximum charging.
This is meant to tie in with a [planned push to home-assistant](https://github.com/alandtse/home-assistant/tree/teslaupdates) exposing those features.  I haven't toxed my fork yet so haven't submitted a pull to home-assistant yet. I'm assuming this will end up as revision 0.0.20 of teslajsonpy, but let me know if it's a different version.
=> Adding additional switches and sensors

teslajsonpy/controller.py, teslajsonpy/vehicle.py
=> Adding update toggle for vehicles

teslajsonpy/BinarySensor.py
=> Removing extraneous . after sensor

teslajsonpy/Lock.py, teslajsonpy/controller.py
The lock is locked when:
- The door is closed
- The door is opened and the charging cable is locked
The lock is unlocked when:
- The door is opened and cable is not locked.
This should fix issue #15
=> Adding charger door lock

teslajsonpy/controller.py
Fix indentation for last_update polling of online vehicles. Fixes (#38)
=> Fix bug where list of online vehicles not updated

teslajsonpy/controller.py
Potential fix for [repeated get_vehicles issue.](https://github.com/home-assistant/home-assistant/issues/29922)
=> fix(controller): add lock for get_vehicles in update

setup.py
=> fix(setup.py): update required libraries

teslajsonpy/lock.py
Tesla will automatically relock so the lock state may not match the internal known
state and prevent a lock/unlock.
=> fix: remove checks for state for lock/unlock

teslajsonpy/__init__.py, teslajsonpy/battery_sensor.py, teslajsonpy/binary_sensor.py, teslajsonpy/charger.py, teslajsonpy/climate.py, teslajsonpy/connection.py, teslajsonpy/controller.py, teslajsonpy/exceptions.py, teslajsonpy/gps.py, teslajsonpy/lock.py, teslajsonpy/sentry_mode.py, teslajsonpy/vehicle.py, tests/tesla_mock.py, tests/unit_tests/test_climate.py
Requires [this version of Tesla to test.](https://github.com/alandtse/home-assistant/tree/tesla_defrost)
closes #62
=> feat: add defrost mode

teslajsonpy/controller.py
Fixes a race condition where different entities could modify the
online state.
=> fix: place car updates behind main lock

teslajsonpy/__version__.py, teslajsonpy/connection.py
Will address https://github.com/home-assistant/core/issues/37106
=> Address HA report #37106

teslajsonpy/controller.py
=> Add option for filtering cars by VIN

teslajsonpy/controller.py
This should resolve a situation where a user chooses a bigger
update_interval.
Addresses #HA37340
=> fix: use max of update_interval and SLEEP_INTERVAL

teslajsonpy/controller.py
The wake_up command was stuck in a deadlock waiting for the update lock
to release. Renamed controller_lock to make it clear it's for access to
the update function instead. Will evaluate whether a lock needs to be
placed on the self.car_online array.
=> fix: change controller_lock to be a function lock

teslajsonpy/binary_sensor.py
=> fix: change sensor_type of update sensor to None

teslajsonpy/homeassistant/charger.py, tests/unit_tests/homeassistant/test_charging_sensor.py
Closes https://github.com/zabuldon/teslajsonpy/issues/114
=> Add charge limit soc

Pipfile.lock
typing-extension markers appeared somehow. That was breaking the ci.
=> build(deps): update deps

Pipfile, Pipfile.lock, setup.cfg, teslajsonpy/connection.py, teslajsonpy/controller.py, teslajsonpy/exceptions.py, teslajsonpy/teslaproxy.py
=> feat: add mfa support

Pipfile, Pipfile.lock
Fix issue where proxy receives non-matching host
=> fix: bump deps

Pipfile, Pipfile.lock, teslajsonpy/const.py
Auth.cn should automatically redirect non-Chinese accounts
=> feat: use auth.cn as initial start

teslajsonpy/controller.py, teslajsonpy/homeassistant/heated_seats.py, tests/unit_tests/homeassistant/test_heated_seat.py
I added an abstraction and tests to control the heated seats.  Wanted to set up an automation to turn these on when the outside temp is low.
=> add heated seats switch

pyproject.toml, setup.cfg
Reverts zabuldon/teslajsonpy#182
=> Revert "build: fix poetry building"

poetry.lock, pylintrc
Fix bug when logging in to China by proxy
=> fix: fix multiple cookies error

AUTHORS.md, teslajsonpy/controller.py, teslajsonpy/homeassistant/heated_seats.py, teslajsonpy/homeassistant/heated_steering_wheel.py, tests/unit_tests/homeassistant/test_heated_seat.py, tests/unit_tests/homeassistant/test_heated_steering_wheel.py
Hello, 
I don't usually add to Open Source, so please go easy :)
As a pre-cursor to adding heated Steering Wheel support into Home Assistant, I've added the steering wheel support into this library.
Also, Heated seats, although in the library, was never implemented in Home Assistant.
Home Assistant now supports "Select" entities, which works really nicely for heated seats.
If you approve this Pull request, i'll then do another for Home Assistant directly to add this functionality.
Added Tests and confirmed linting as required.
=> Add Heating Steering Wheel Support & Move Heated Seats to SELECT

AUTHORS.md, poetry.lock, teslajsonpy/const.py, teslajsonpy/controller.py, teslajsonpy/homeassistant/power.py, tests/tesla_mock.py, tests/unit_tests/homeassistant/test_power_sensor.py
Add Solar Panel support.
BREAKING CHANGE: Product_type added to functions (get, post, command) to differentiate between vehicles or energy sites. data_request rename to vehicle_data_request. 
closes #49 
closes #212
=> feat: added support for energy sites  (#219)

teslajsonpy/homeassistant/vehicle.py, teslajsonpy/teslaproxy.py
Fixes #221 
lint errors generated by `pylint`
=> Fixed lint errors

teslajsonpy/connection.py, teslajsonpy/controller.py, teslajsonpy/endpoints.json, teslajsonpy/homeassistant/charger.py, teslajsonpy/homeassistant/climate.py, teslajsonpy/homeassistant/heated_seats.py, teslajsonpy/homeassistant/heated_steering_wheel.py, teslajsonpy/homeassistant/lock.py, teslajsonpy/homeassistant/sentry_mode.py, teslajsonpy/homeassistant/trunk.py, tests/tesla_mock.py
Uses data from https://github.com/tdorssers/TeslaPy/blob/master/teslapy/endpoints.json
closes #216
=> refactor: switch to api convenience function

teslajsonpy/connection.py, teslajsonpy/controller.py
This allows China users to login with tokens.
=> fix: allow specification of auth_domain

teslajsonpy/homeassistant/binary_sensor.py, tests/unit_tests/homeassistant/test_online_sensor.py
Adding "update_interval" as an attribute to the online-sensor, to be able to use it in automations for better control of polling
=> Add update_interval as an attribute

teslajsonpy/endpoints.json
https://github.com/tdorssers/TeslaPy/blob/7f8c86c7b501a7e59fb24e79eb8cae367b965b39/teslapy/endpoints.json
=> feat: sync endpoints.json with teslapy

teslajsonpy/controller.py, tests/tesla_mock.py, tests/unit_tests/homeassistant/test_battery_sensor.py, tests/unit_tests/homeassistant/test_calculate_update_interval.py, tests/unit_tests/homeassistant/test_charger_connection_sensor.py, tests/unit_tests/homeassistant/test_charger_lock.py, tests/unit_tests/homeassistant/test_charger_switch.py, tests/unit_tests/homeassistant/test_charging_sensor.py, tests/unit_tests/homeassistant/test_climate.py, tests/unit_tests/homeassistant/test_frunk_lock.py, tests/unit_tests/homeassistant/test_gps_tracker.py, tests/unit_tests/homeassistant/test_heated_seat.py, tests/unit_tests/homeassistant/test_heated_steering_wheel.py, tests/unit_tests/homeassistant/test_helper_functions.py, tests/unit_tests/homeassistant/test_lock.py, tests/unit_tests/homeassistant/test_odometer_sensor.py, tests/unit_tests/homeassistant/test_parking_sensor.py, tests/unit_tests/homeassistant/test_range_sensor.py, tests/unit_tests/homeassistant/test_range_switch.py, tests/unit_tests/homeassistant/test_sentry_mode_switch.py, tests/unit_tests/homeassistant/test_temp_sensor.py, tests/unit_tests/homeassistant/test_trunk_lock.py, tests/unit_tests/homeassistant/test_vehicle_device.py
Sorry this looks so intimidating.
This PR incorporates helper functions for setting and getting most private and internal variables. 
I am marking it as a draft, as I am still working on it, but it is getting to a state that actually works pretty well now, so I would appreciate any feedback. 
When I migrated code to the new helper functions, I also needed to update almost all the tests.  That is why so many files have been changed.  All actual code change is in controller.py. The rest are in the different tests.
On the ther hand, almost all tests are now using the real helper functions and code instead of mock functions. This makes the tests more relevant, I hope.
I also updated all the existing helper functions to be consistent in what parameters they accept, and what they return.  And …
=> Use helper functions

teslajsonpy/homeassistant/gps.py
=> Fix `get_location()` not updating if car facing north

teslajsonpy/homeassistant/binary_sensor.py, tests/unit_tests/homeassistant/test_online_sensor.py
* New vehicle_data attribute for online sensor containing all the data returned as json string
=> feat: provide all data in home assistant sensor as json string (#279)

teslajsonpy/const.py, teslajsonpy/controller.py, teslajsonpy/homeassistant/binary_sensor.py, tests/unit_tests/test_polling_interval.py
* Add per vehicle polling interval
* Fixed lint/flake error
* Add polling interval tests
* Added tests for 2nd VIN
* Make update interval constant in const.py
=> feat: add per vehicle polling interval (#281)

teslajsonpy/endpoints.json
https://github.com/tdorssers/TeslaPy/commit/f6b250edddabe1c1938665f47bfb14d54ee131f0
=> feat: update endpoints.json for version 4.5

setup.cfg, teslajsonpy/connection.py, teslajsonpy/controller.py, teslajsonpy/homeassistant/binary_sensor.py, teslajsonpy/homeassistant/gps.py
Reverts zabuldon/teslajsonpy#289
=> Revert "Remove get bearer token step"

teslajsonpy/homeassistant/charger.py
If the value was the same as the last update last_reset would be set
Fixes #288
=> Adjust last_reset calculation to handle charge_energy_added being the same

teslajsonpy/homeassistant/power.py
Adding attribute enabled_by_default to EnergySiteDevice.
=> Add attribute enabled_by_default to EnergySiteDevice

teslajsonpy/controller.py
Closes https://github.com/alandtse/tesla/issues/193
=> fix: Remove duplicate ChargeStateDataSensor (#306)

teslajsonpy/controller.py, teslajsonpy/homeassistant/heated_seats.py
Add 3rd row heated seats, disabled by default as most users won't have it.
=> Add 3rd row heated seats

teslajsonpy/homeassistant/heated_seats.py, teslajsonpy/homeassistant/heated_steering_wheel.py
This PR is to have the heated seats and steering wheel disabled by default.
PR [#205](https://github.com/alandtse/tesla/pull/205) for the tesla component will ensure that those supported by the vehicle will become enabled
=> Disable heated seats and steering wheel by default

teslajsonpy/endpoints.json
Hello,
There are many new Commands in the new version of the app, 4.7.0
Just looking to update endpoints.json so we can take advantage of the new commands like activating Dog Mode
new endpoints file gathered from
https://github.com/timdorr/tesla-api/blob/master/docs/miscellaneous/endpoints.md
=> Update endpoints.json to app version 4.7.0

teslajsonpy/homeassistant/power.py
=> fix: improve handling on 0 Watts spurious power reads (#317)

.github/workflows/semantic_release.yml
relekang/python-semantic-release#442
=> ci: pin psr to v7.28.1

.github/workflows/build_docs.yml, .github/workflows/semantic_release.yml
=> ci: seperate doc building

teslajsonpy/car.py, tests/unit_tests/test_car.py
Adds tire pressure monitor sensors, doors and window properties.
=> feat: add tpms, door and window properties

teslajsonpy/car.py, tests/unit_tests/test_car.py
I guess my formatted decided to make some changes. coverage/lint/typing went okay, Not sure what happened there.
=> feat: add valet mode command and property

teslajsonpy/car.py, tests/unit_tests/test_car.py
* add valet mode command and property
* adj params
* add param test
* update valet_mode arguments
* duplicate test
=> fix: add Valet mode optional argument (#374)

teslajsonpy/controller.py
=> fix: correct typo in wake_up call

teslajsonpy/car.py, tests/unit_tests/test_car.py
related to https://github.com/alandtse/tesla/issues/466
=> fix: handle option codes unavailable

teslajsonpy/endpoints.json
I believe this will fix the navigation issue highlighted by Brian Gates and documented at https://tesla-api.timdorr.com/vehicle/commands/sharing
closes #399
=> fix: update endpoints.json for sharing (#399)

teslajsonpy/connection.py
orjson can decode bytes directly without the need to convert it to text first.
Avoid calling `.text` since it has to do extra processing under the hood in debug as well
=> perf: avoid bytes to text conversion overhead

.github/workflows/semantic_release.yml
https://github.com/python-semantic-release/python-semantic-release/issues/654#issuecomment-1646922959
=> ci: lock PSR to 7.x

.github/workflows/test_and_lint.yaml, teslajsonpy/controller.py, teslajsonpy/endpoints.json, teslajsonpy/energy.py, tests/tesla_mock.py, tests/unit_tests/test_energy.py
Fixes deprecation of BATTERY_DATA and BATTERY_SUMMARY
=> fix: update powerwall endpoints (#428)

teslajsonpy/energy.py
Using nameplate energy * percentage charged to calculate energy left.
=> fix: fix Energy Left

teslajsonpy/controller.py
create_default_context does blocking I/O in the event loop
related issue https://github.com/alandtse/tesla/issues/1029
=> fix: avoid calling create_default_context unless needed

AUTHORS.md, poetry.lock, pylintrc, teslajsonpy/connection.py, teslajsonpy/const.py, teslajsonpy/controller.py, tests/unit_tests/test_polling_interval.py
Related to issue: #481 
Extras:
- Removed useless DRIVER_INTERVAL usage in connection.py
=> feat: added configurable parameter driving_interval
